data:
  input:
    path: ../data_samples/dataset.csv
    separator: '$'
  extraction:
    function:
      path: extraction
  output:
    file:
      name: results_old
      separator: ','
  splitting:
    runs: 2
    folding:
      method: KFOLD
      number: 2
      seeds:
        from_list:
        from_file: ../data_samples/seeds.yaml